### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marcoc1712/musicbrainzws2-java#6]
```
Hi, just wanted to clarify the licence for the library. On Google code it is 
showing up as GPL but the copying.txt in the source makes it look like it 
isn't. Could you please let me know if it is GPL?

Thanks
```

Original issue reported on code.google.com by `antoine....@fortiumtech.com` on 5 Feb 2015 at 8:41

**Comment by marcoc1712** [comment]
No, the whole project is not, becouse it was not in origin and I'm not allowed to change original terms, but everything I added is GNU GPL v3.

Hope it helps.
